### ISSUE TITLE
Maybe gentoo specific: I can use qmake QT5 but includes are QT4

### ISSUE THREAD

**Issue by killerhippy** [raoulh/moolticute#1]
build # qmake -qt=5 ../Moolticute.pro
build # make
( test -e Makefile.daemon || /usr/lib64/qt5/bin/qmake /usr/local/src/git/moolticute/daemon.pro -o Makefile.daemon ) && make -f Makefile.daemon 
make[1]: Entering directory '/usr/local/src/git/moolticute/build'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../../moolticute -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I. -I../../moolticute -I. -o main_daemon.o ../src/main_daemon.cpp
In file included from ../src/main_daemon.cpp:20:0:
../src/AppDaemon.h:22:24: fatal error: QApplication: No such file or directory
 #include <QApplication>
                        ^
compilation terminated.
Makefile.daemon:313: recipe for target 'main_daemon.o' failed
make[1]: *** [main_daemon.o] Error 1
make[1]: Leaving directory '/usr/local/src/git/moolticute/build'
Makefile:41: recipe for target 'sub-daemon-pro-make_first' failed
make: *** [sub-daemon-pro-make_first] Error 2

**Comment by raoulh** [comment]
Are you using the Qt5 qmake binary? it seems you are trying to run the qmake from your qt4 installation. On most distro qmake is a link to the real binary, aka qmake-qt4/qmake-qt5. I don't know how it is on Gentoo.

**Comment by killerhippy** [comment]
Gentoo has a QT4, QT5 mix up with QT4 as default.

Your assumption is correct, see for yourself:
$ ls -l /etc/xdg/qtchooser/
total 12
lrwxrwxrwx 1 root root 28 Okt 29 08:21 4.conf -> qt4-x86_64-pc-linux-gnu.conf
lrwxrwxrwx 1 root root 28 Okt 29 06:14 5.conf -> qt5-x86_64-pc-linux-gnu.conf
lrwxrwxrwx 1 root root  8 Okt 29 08:21 default.conf -> qt4.conf
-rw-r--r-- 1 root root 34 Okt 29 08:21 qt4-i686-pc-linux-gnu.conf
-rw-r--r-- 1 root root 34 Okt 29 08:21 qt4-x86_64-pc-linux-gnu.conf
lrwxrwxrwx 1 root root 28 Okt 29 08:21 qt4.conf -> qt4-x86_64-pc-linux-gnu.conf
-rw-r--r-- 1 root root 30 Okt 29 06:14 qt5-x86_64-pc-linux-gnu.conf
lrwxrwxrwx 1 root root 28 Okt 29 06:14 qt5.conf -> qt5-x86_64-pc-linux-gnu.conf

changing default.conf pointing to 5.conf does not help neither.

It is the includes, they are always QT4.

**Comment by killerhippy** [comment]
$ cat /etc/xdg/qtchooser/qt?-x86_64-pc-linux-gnu.conf
/usr/lib64/qt4/bin
/usr/lib64/qt4
/usr/lib64/qt5/bin
/usr/lib64

I've already checked pointing default.conf to 5.conf and changed /usr/lib64 to /usr/usr/lib64 /lib64/qt5 but includes stay QT4.

**Comment by killerhippy** [comment]
(dropped two postings which were silly)
Yes, I use the QT5 qmake binary, if I use qmake -qt=5
This is not the problem I assume, it is the QT4 includes. What do you think?

**Comment by raoulh** [comment]
No, there is no such option for qmake. To be sure you can try qmake --version, and see what version go qmake/Qt is used. When I googled, it says that qmake for Qt5 on gentoo is located in /usr/lib64/qt5/bin/qmake try using this one.

**Comment by killerhippy** [comment]
# which qmake
/usr/bin/qmake
# file /usr/bin/qmake
/usr/bin/qmake: symbolic link to qtchooser

qtchooser has the option "-qt=<qt-version>" which allows you to choose the version you want to use.
With the help of https://forums.gentoo.org/viewtopic-p-7841136.html I could solve my issue.
All that was missing was a dev-qt/qtwebsockets package missing at my system. After installing it, moolticute compiled fine.

Steps:
mkdir build
cd build
qmake -qt=5 ../Moolticute.pro
make

**Comment by killerhippy** [comment]
case closed

**Comment by raoulh** [comment]
Nice to hear you resolve the issue. That's true anyway that on many distro Qt modules are split in multiple packages. I will detail the needed Qt packages in the readme. Thanks!

**Comment by NicoHood** [comment]
I get the following error:
```
make
( test -e Makefile.daemon || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /moolticute/daemon.pro -o Makefile.daemon ) && make -f Makefile.daemon 
Project ERROR: Unknown module(s) in QT: websockets
make: *** [sub-daemon-pro-make_first] Error 3
```

```
qmake --version
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
```

I used qt of ubuntu 14.04 (Elementary OS) and not a manual installation.

**Comment by raoulh** [comment]
Hey,

Moolticute is using features from Qt that requires Qt 5.4 at least. 5.2 does not have the websocket module...

You would need to upgrade your ubuntu to be able to compile moolticute

**Comment by NicoHood** [comment]
```
qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
```

I used ubuntu 16.04 now but still got the exact same error.

```
  171  sudo apt-get install libusb-dev 
  172  sudo apt-get install libusb-1.0-0
  173  sudo apt-get install libusb-1.0-0-dev 
  174  sudo apt-get install qt-sdk 
  176  sudo apt-get install qt5-qmake
  178  sudo apt-get install qt5-default
  179  sudo apt-get install qtcreator
``

**Comment by raoulh** [comment]
Did you install libqt5websockets5-dev ?

**Comment by NicoHood** [comment]
Now it worked. It would be cool if you could add those dependencies to the readme as simple `sudo apt-get install` paste.
