### ISSUE TITLE
MoolticuteApp-v0.2.3-alpha.dmg - Not working for me.

### ISSUE THREAD

**Issue by Gastonius** [raoulh/moolticute#10]
Hello Raoulh!

Installed latest version. Started normally.

Won't work for me neither in FF or Chrome.

Here's some debug info:

Chrome - Context and fallback appears to be right, the BLUE part is raw from what I got from Moolticute:

<img width="996" alt="screen shot 2016-10-06 at 6 14 30 pm" src="https://cloud.githubusercontent.com/assets/3153540/19170973/e9e02e5c-8bf0-11e6-80b3-de0208323e9f.png">

Log - From another request / No subdomain.

<img width="830" alt="screen shot 2016-10-06 at 6 11 44 pm" src="https://cloud.githubusercontent.com/assets/3153540/19171004/14b68ebe-8bf1-11e6-8c89-781fec6638b7.png">

Could it be me? Let me know how can I help!

**Comment by raoulh** [comment]
From the log, I think you have something else running like the official Mooltipass chrome app. Or another moolticuted process, is it the case?

**Comment by Gastonius** [comment]
App wasn't running. But it seems Chrome left something at memory, because as soon as I restarted Chrome entirely (and uninstalled the app), it started to work.
