### ISSUE TITLE
Win 10: Cannot exit the credentials tab

### ISSUE THREAD

**Issue by alanrick** [raoulh/moolticute#109]
When browsing the credentials ("Credentials Management) I cannot exit to another tab (e.g. "About"). 
Clicking on the other tab has no effect, and pressing "discard changes" doesn't help.

I'm not ruling out a usability issue :)

Windows 10 64 bit

**Comment by raoulh** [comment]
Hi,

To exit the credential management tab you need to press the "discard
changes" (and keep the button pressed) until it exits...

--
Raoul Hecky

2017-09-22 14:01 GMT+02:00 alanrick <notifications@github.com>:

**Comment by alanrick** [comment]
duh... of course...Same as Mooltipass.
However, if you click on the button it flickers, but  you don't see the the text of the replacement button because it reverts too fast. And even when you press continuously you see a red (frightening) button and the text is too truncated to read.
"ld to ....chan"

Why not have the instructional text above the button?

**Comment by raoulh** [comment]
I agree. This button is not well done. We need to investigate for something
better.

Thanks

--
Raoul Hecky

2017-09-22 15:03 GMT+02:00 alanrick <notifications@github.com>:

**Comment by limpkin** [comment]
@azubieta : maybe change the red into some kind of grey, and force the animation for 1s at least, regardless if the button is pressed or not?
