### ISSUE TITLE
Error with credential management mode if wrong password

### ISSUE THREAD

**Issue by penoud** [raoulh/moolticute#113]
If you request to manage credential from the moolticute your device will ask you credential confirmation. If you type a wrong password on the mooltipass, and retry with the good one, the application did not detect it and the application ask you to unlock your device. The device was unlock at this time. The solution is to unplug/plug the device.

app version v0.9.8-beta, with mooltipass mini v1.2_mini on Debian 9

**Comment by limpkin** [comment]
salut !
tu peux expliquer le bug en francais? je suis pas sur de suivre...

**Comment by penoud** [comment]
Salut,
1) Demande dans l'application de passer en mode gestion des identifiants
2) Tapez un mot de passe faux sur le mootlpass
3) Essayer une deuxième fois et entrer le bon mot de passe
4) L'application me dit alors que mon mooltipass est verrouillé
La seule solution est de débrancher le mooltipass et de recommencer en 1) et ne pas se tromper. Sinon l'appli se bloque à nouveau.
PS: mis à part ce détail ça marche nikel, j'apprécie la gestion de fichier pour mes clefs ssh. Beau boulot

**Comment by raoulh** [comment]
Je n'arrive pas a reproduire, ca fonctionne chez moi.
1.  Aller en mmm
2. tapper un mdp faux
3. tapper le mdp correct
4. l'app rentre bien dans le mmm

**Comment by limpkin** [comment]
pareil... j'arrive pas à reproduire :(

**Comment by nemunaire** [comment]
J'ai réussi à reproduire le bug. J'ai obtenu une boîte de dialogue avec :

> Erreur de gestion de la mémoire
> Une erreur est survenue lors du passage en mode de gestion de la mémoire.
> Couldn't Load Database, Please Approve Prompt On Device

Voici à quoi a ressemblé la reproduction du bug chez moi:

1. Aller en mmm
1. approuver le mmm sur le mooltipass
1. taper un mdp faux
1. taper le mdp correct
1. bizarrement, à ce stade, la procédure recommence (mais l'interface continue bien à attendre le mmm, elle n'est pas verrouillée) : approuver le mmm sur le mooltipass
1. taper un mdp faux
1. taper le mdp correct
1. boîte de dialogue d'avertissement + moolticute verrouillé

Voici les [logs du deamon](https://github.com/raoulh/moolticute/files/1351259/moolticuted.log) pour cette session.

**Comment by limpkin** [comment]
ok... on pense que c'est un bug lié à linux... la prochaine version de MC
contient un fix qui pourrait résoudre ce souci :)

2017-10-03 7:55 GMT+02:00 nemunaire <notifications@github.com>:

**Comment by raoulh** [comment]
Ce serait bien que @penoud et @nemunaire testent d'abord le git master avant de releaser

**Comment by limpkin** [comment]
@raoulh : I'm seeing **a lot** of retries that may break something. Could you implement #101 so they can try master again?

**Comment by limpkin** [comment]
ok I think I got it! please retry from master

**Comment by limpkin** [comment]
try again! it should be good now :)

**Comment by nemunaire** [comment]
I confirm, this is now fixed on master!
