### ISSUE TITLE
Orphan child issue

### ISSUE THREAD

**Issue by NoahAndrews** [raoulh/moolticute#115]
After the Chrome extension created a new credential with an incorrect username, I attempted to change the username to NoahAndrews through Moolticute's credential management mode.

When I clicked the "Save all changes" button, I got this error: 
![image](https://user-images.githubusercontent.com/10224994/31058514-e643dfee-a6c2-11e7-862f-7334a4559dfe.png)

Now, every time I click "save all changes" I get the same error, even if I didn't change anything. If I did change anything, it doesn't get saved. The original username change never got saved either.

The relevant-looking lines from the log:

![image](https://user-images.githubusercontent.com/10224994/31058545-85a4c166-a6c3-11e7-90c9-8615fd3830a6.png)

Those lines show up every time I press "save all changes".

**Comment by limpkin** [comment]
Hello Noah,

Could you let us know the service name for which you created that username?

That's very odd...
Mathieu

**Comment by NoahAndrews** [comment]
nelnetsolutions.com

**Comment by limpkin** [comment]
Hmm that's odd.

If you trust me, can you send me in private (you already know my private
email address IIRC) your complete log when going into MMM, changing the
username, and saving?

**Comment by NoahAndrews** [comment]
Sure, I'll see if I can reproduce this on my other Mooltipass.

**Comment by NoahAndrews** [comment]
Well. It turns out that that orphaned NoahAndrews entry wasn't created today. My other Mooltipass (which I use much less often) had the same error. I'm sending you the full log for entering credentials mode and immediately pressing "save all changes" on the OG Mooltipass.

**Comment by NoahAndrews** [comment]
Actually, I found the relevant parts of the log, so I'll just put it here. It seems the issue is related to a username change I apparently attempted to make a long time ago that only changed the capitalization.

![image](https://user-images.githubusercontent.com/10224994/31058794-d34c97aa-a6c7-11e7-843c-7506c4ec93ce.png)

![image](https://user-images.githubusercontent.com/10224994/31058786-9c3fae50-a6c7-11e7-96c5-898273b551a0.png)

**Comment by limpkin** [comment]
Ohhh, very nice find!

@raoulh : https://github.com/raoulh/moolticute/blob/master/src/MPDevice.cpp#L2526 seems default to caseinsensitive? http://doc.qt.io/qt-5/qstring.html#compare-1

**Comment by raoulh** [comment]
No, the default is Qt::CaseSensitive

**Comment by limpkin** [comment]
Could you quickly change that? :)

**Comment by limpkin** [comment]
Noah: do you have other usernames for that service by any chance?

On Oct 2, 2017 9:04 AM, "Limpkin" <limpkin@limpkin.fr> wrote:

Could you quickly change that? :)

**Comment by NoahAndrews** [comment]
no other usernames for cyberquests

**Comment by limpkin** [comment]
@raoulh : found the problem. For some reason, if there is one user "userrecov1" and another "UserRecov1" inside the database, only one is displayed on the GUI.

Here's what the GUI receives:

DEBUG: WSClient.cpp:124 - New message:  {"data":{"data_nodes":[],"login_nodes":[
{"childs":[
{"address":[81,15],"date_created":"2017-07-14","date_last_used":"2017-10-02","description":"","favorite":-1,"login":"UserRecov1","password_enc":[170,183,113,93,134,104,8,249,155,182,86,249,211,4,243,151,68,214,88,53,250,93,140,131,12,96,74,10,115,117,1,56]},
{"address":[-63,16],"date_created":"2017-10-02","date_last_used":"2017-10-02","description":"","favorite":-1,"login":"userrecov1","password_enc":[57,160,78,155,88,159,6,114,111,205,130,217,33,14,176,129,94,158,169,48,204,183,129,149,183,51,82,237,252,39,124,242]},
{"address":[88,15],"date_created":"2017-07-14","date_last_used":"2017-10-02","description":"","favorite":-1,"login":"userrecov2","password_enc":[222,215,68,96,135,240,11,122,185,124,121,236,147,172,6,116,50,30,174,33,21,19,182,246,26,62,11,0,152,105,153,16]},
......

yet only one is displayed:

![image](https://user-images.githubusercontent.com/6170291/31096031-2429f0fc-a7bb-11e7-88bf-3d918c3b9926.png)
