### ISSUE TITLE
Moolticute sometimes starts with the memory management mode on in the credentials tab

### ISSUE THREAD

**Issue by limpkin** [raoulh/moolticute#19]
Title pretty much says everything.
Not sure if it matters, but this issue started after I started working on moolticute

**Comment by limpkin** [comment]
actually the MMM is only enabled if the chrome app is already running on windows... i'm therefore guessing some fight over the usb bus.
However, why doesn't moolticute has MMM disabled at boot by default?

**Comment by raoulh** [comment]
should be fixed in 92597e0ddae0d38e7e3aba8ebe35184c5b9fa2ac
