### ISSUE TITLE
Cannot connect to device

### ISSUE THREAD

**Issue by NicoHood** [raoulh/moolticute#2]
Once I got the app compile now, I am not able to connect to mooltipass.

```
./MoolticuteApp 
DEBUG: :0 - Websocket disconnect
DEBUG: :0 - Websocket error:  "Connection refused"
DEBUG: :0 - Websocket open()
```

I am using Ubuntu Mate 16.04 and I've enable the udev rules. The chrome app works, I also closed the chrome app before launching moolticute. I tried replugging and unlocking.

**Comment by limpkin** [comment]
Disable the application in the extension tab of chrome

**Comment by NicoHood** [comment]
No. Moolticute did not work, even before I had not even installed chrome. So that cannot be the problem. I installed chrome afterwards to verify the udev rule works.

**Comment by raoulh** [comment]
Did you start the moolticute daemon first?
`./moolticuted`

The client needs to connect to a running daemon

**Comment by NicoHood** [comment]
Ah! that should be noted in the readme as a "usage" section.

However I got another error:
Websocket connected
mp_disconnected (2 times)

The moolticuted deamon only shows warnings when opening the devices. I also tried replugging etc.

**Comment by NicoHood** [comment]
Any ideas?

**Comment by raoulh** [comment]
You need correct udev rules for your device and libusb. Do you have them configured?

**Comment by NicoHood** [comment]
I used this instruction:
http://www.themooltipass.com/udev_rule.txt

I only used this line:
```
root@myusers-vubuntu:~# echo "KERNEL==\"hidraw*\", SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"16d0\", ATTRS{idProduct}==\"09a0\", MODE=\"0664\", GROUP=\"plugdev\"" > /etc/udev/rules.d/50-mooltipass.rules
```

This works under ubuntu 16.04 with the mooltipass chrome app but not with moolticute!?

**Comment by raoulh** [comment]
No it does work as Moolticute needs libusb access and does not use hidraw.
Include the udev rule for libusb access and it will work

**Comment by NicoHood** [comment]
Which libusb rule? How does it look like?

**Comment by raoulh** [comment]
The one for libusb that is written in http://www.themooltipass.com/udev_rule.txt
Something like:
```
echo "ATTRS{idVendor}==\"16d0\", ATTRS{idProduct}==\"09a0\", SYMLINK+=\"mooltipass\", MODE=\"0664\", GROUP=\"plugdev\"" > /etc/udev/rules.d/50-mooltipass.rules
```

**Comment by NicoHood** [comment]
Now it works. I did no know that there is such a difference. Please add it to the readme.

Do you also know how much has changed to the app since you last updated moolticute? Because I really would like to use moolticute instead of the chrome app. The chrome app honstely has too many unsolved bugs, which I am unable to fix. For a c++ app this might be different, while still a challenge.

**Comment by raoulh** [comment]
For now in moolticute, in memory management mode you can only view your credentials, but not add/delete them. The code for handling device memory node in the moolticute daemon is not finished/working yet.
