### ISSUE TITLE
Moolticuted listening port

### ISSUE THREAD

**Issue by bobsaintcool** [raoulh/moolticute#21]
As the listening port of moolticuted is hardcoded it will be hard to allow two different user to run the daemon on the same system.

Is this something expected ?

**Comment by raoulh** [comment]
You can't have multiple device connected at the same time anyway. So what's the point of running multiple instance of moolticuted?
If a second user needs access to his device, he can use the already running daemon right?

**Comment by bobsaintcool** [comment]
Ok so I was missleaded after an conversation about this on IRC.

So I should change the systemd service file to make moolticuted an systemd daemon instead of user daemon ?

**Comment by raoulh** [comment]
I think it would be better yes.

Another problem, the port is also hardcoded in the firefox/chrome browser extensions.
