### ISSUE TITLE
Unable to build QApplication: No such file or directory

### ISSUE THREAD

**Issue by bertvandepoel** [raoulh/moolticute#24]
Something seems to be wrong, both qtcreator and the CLI make yield the following problem:

bert@bert-virtual-machine:~/moolticute/build$ qmake ../Moolticute.pro
bert@bert-virtual-machine:~/moolticute/build$ make
( test -e Makefile.daemon || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/bert/moolticute/daemon.pro -o Makefile.daemon ) && make -f Makefile.daemon 
make[1]: Entering directory '/home/bert/moolticute/build'
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DMC_INSTALL_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../moolticute -I. -isystem /usr/include/libusb-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o UsbMonitor_linux.o ../src/UsbMonitor_linux.cpp
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DMC_INSTALL_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../moolticute -I. -isystem /usr/include/libusb-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o MPDevice_linux.o ../src/MPDevice_linux.cpp
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DMC_INSTALL_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../moolticute -I. -isystem /usr/include/libusb-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main_daemon.o ../src/main_daemon.cpp
In file included from ../src/main_daemon.cpp:19:0:
../src/AppDaemon.h:26:24: fatal error: QApplication: No such file or directory
compilation terminated.
Makefile.daemon:561: recipe for target 'main_daemon.o' failed
make[1]: *** [main_daemon.o] Error 1
make[1]: Leaving directory '/home/bert/moolticute/build'
Makefile:41: recipe for target 'sub-daemon-pro-make_first' failed
make: *** [sub-daemon-pro-make_first] Error 2

I think there's some kind of regression bug, since it's fixed when I revert one commit back from the latest one (a765c8525c69816a0b9e6c793aa289aee6cc5eb7 to 9a97fc17dbeccb4483efdcb5302ab78109652aa5)

**Comment by raoulh** [comment]
Please, try again with git master, it should be fixed now.

--
Raoul Hecky

2017-02-06 1:59 GMT+01:00 Bert Van de Poel <notifications@github.com>:
