### ISSUE TITLE
Bug when deleting ssh keys

### ISSUE THREAD

**Issue by limpkin** [raoulh/moolticute#27]
While using Moolticute add your ssh keys to your MPM using ssh-add.
Delete your keys using ssh-add -D
Allow all prompts on the MPM
The last prompt will say "Update Data For: ????????"
Once you allow the last prompt the MPM will freeze up.

**Comment by raoulh** [comment]
Fixed in 311e6ac00b0695ecaaa2590939286eaa67f06987
