### ISSUE TITLE
Missing dict-src.h file needed for compilation

### ISSUE THREAD

**Issue by seemuth** [raoulh/moolticute#34]
I'm using Qt 5.8 on Debian Jessie. When I try to build through Qt Creator, it throws a compilation error due to a missing dict-src.h file.

```
gcc -c -pipe -g -Wall -W -D_REENTRANT -fPIC -DMC_INSTALL_PREFIX=\"/usr/local\" -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../mooltipass/moolticute -I. -I../mooltipass/moolticute/src/QtAwesome/QtAwesome -I../mooltipass/moolticute/src -I../mooltipass/moolticute/src/zxcvbn-c -I../../Qt/5.8/gcc_64/include -I../../Qt/5.8/gcc_64/include/QtWidgets -I../../Qt/5.8/gcc_64/include/QtGui -I../../Qt/5.8/gcc_64/include/QtWebSockets -I../../Qt/5.8/gcc_64/include/QtNetwork -I../../Qt/5.8/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../../Qt/5.8/gcc_64/mkspecs/linux-g++ -o zxcvbn.o ../mooltipass/moolticute/src/zxcvbn-c/zxcvbn.c
../mooltipass/moolticute/src/zxcvbn-c/zxcvbn.c:456:22: fatal error: dict-src.h: No such file or directory
 #include "dict-src.h"
                      ^
compilation terminated.
```

This happens regardless of if I build in Debug mode or Release mode.

**Comment by limpkin** [comment]
this file was committed 8 hours ago no?

https://github.com/raoulh/moolticute/commit/5f976fa5cc032a91439fc99a022814d5faf32887

**Comment by seemuth** [comment]
Hah! I must have cloned the repo at just the wrong time. Thanks!

**Comment by limpkin** [comment]
no worries! do you have a standard or mini mooltipass?

**Comment by seemuth** [comment]
Mini, (or I will in a couple of weeks when it arrives)! 😃

**Comment by limpkin** [comment]
which color did you pick? if you're comfortable with qt/c++ I can send you one in advance...

**Comment by limpkin** [comment]
mmmhh I'm seeing a red & blue... do you have much spare time anyways?

**Comment by seemuth** [comment]
Two blue and one red, and 4x extra cards. Thank you very much!

Yep, I use Qt and C++ a lot. I don't have a ton of spare time, but I find that I make the time when there's an "itch to scratch" in my workflow. 😃

**Comment by limpkin** [comment]
great! I'll have one mini shipped your way Monday.

Cheers!

**Comment by seemuth** [comment]
Awesome, thank you very much indeed! 🥇 👍 🎉 🎈

**Comment by limpkin** [comment]
you're welcome! just fyi the unit won't represent the final build quality !
