### ISSUE TITLE
moolticuted critical error: tagPointedNodes: couldn't find parent node with address "" in our list

### ISSUE THREAD

**Issue by seemuth** [raoulh/moolticute#37]
I started using my Mooltipass Mini yesterday and got it set up on my Linux machine with a few shared credentials. At some point I unplugged the Mooltipass while the card was plugged in and unlocked. After that, moolticuted errors out when I plug in the Mooltipass.

The daemon log is available at https://gist.github.com/seemuth/69dce3bd01a815f45eb1ed276ec1823f

> DEBUG: ../moolticute/src/WSServer.cpp:105 - Mooltipass connected
> INFO: ../moolticute/src/MPDevice.cpp:2013 - Checking database...
> CRITICAL: ../moolticute/src/MPDevice.cpp:1487 - tagPointedNodes: couldn't find parent node with address "" in our list
> INFO: ../moolticute/src/MPDevice.cpp:2067 - Number of parent orphans: 0
> INFO: ../moolticute/src/MPDevice.cpp:2068 - Number of children orphans: 0
> INFO: ../moolticute/src/MPDevice.cpp:2069 - Number of data parent orphans: 0
> INFO: ../moolticute/src/MPDevice.cpp:2070 - Number of data children orphans: 0
> INFO: ../moolticute/src/MPDevice.cpp:2108 - Errors were found in the database
> INFO: ../moolticute/src/AsyncJobs.cpp:97 - "Exiting MMM"
> CRITICAL: ../moolticute/src/MPDevice.cpp:2358 - Failed to exit MMM

This error persists even after I erase the Mooltipass and re-initialize the card, and the same error occurs on both Linux systems I tried.

I am able to successfully use the same Mooltipass using the Chrome add-ons on a Mac, so it appears that the hardware itself is still fine. Even on the Linux computers, I can manually choose Login on the Mooltipass itself and have it type in my credentials for me.

My main Linux desktop is `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux`, using i3wm, with Qt version 5.8.0.

**Comment by limpkin** [comment]
Hello,

Does this log happen when you plug the device? If so this is very odd as this is code that should be triggered when one presses the integrity check button.

**Comment by limpkin** [comment]
hello, 

After talking with @raoulh your log output is completely normal.

**Comment by seemuth** [comment]
Sorry, I forgot to make explicit that moolticute doesn't prompt the Mooltipass to produce any credentials (whether through the Firefox plugin or through the moolticute GUI when I try to enter credential management mode). It just sits there without doing anything. This prompted me to dig into the logs, which is when I found the mentioned messages.

**Comment by limpkin** [comment]
that's quite odd indeed...

**Comment by limpkin** [comment]
hello there,

we're currently investigating the problem and will keep you updated. Could you try using moolticute with firefox and see if your problem still persists? thanks!

**Comment by seemuth** [comment]
I plugged my Mooltipass back in today and ran moolticuted, and it 
worked again... until I unplugged it and plugged it back in.

When it is working, I see lots of log messages like:

> DEBUG: ../moolticute/src/WSServerCon.cpp:396 - Update client status 
> changed:  WSServerCon(0x22dc260)
> DEBUG: ../moolticute/src/WSServerCon.cpp:396 - Update client status 
> changed:  WSServerCon(0x2339870)

When it isn't working, I just see messages when I plug in or unplug the 
device:

> DEBUG: ../moolticute/src/UsbMonitor_linux.cpp:55 - 0
> DEBUG: ../moolticute/src/UsbMonitor_linux.cpp:60 - Device removed:  
> 0x16d0 - 0x9a0
> DEBUG: ../moolticute/src/UsbMonitor_linux.cpp:40 - Device added:  
> 0x16d0 - 0x9a0

**UPDATE**: I got it to work once more by `chown`ing `/dev/hidraw5` and 
`/dev/bus/usb/003/025` (according to `lsusb`) to my user. Unfortunately 
it went back to not working again after I unplugged and replugged, even 
after `chown`ing again.

**Comment by seemuth** [comment]
Permissions apparently have nothing to do with the problem. I
plugged in the Mooltipass after leaving it unplugged for a couple of
hours, and it works again (both via Firefox and the moolticute GUI).


When I unplug the device and plug it back in, it's back to not
working. Very strange.

**Comment by limpkin** [comment]
Hello Daniel,

That's quite odd indeed, as you're a contributor, maybe you should come to our irc channel #mooltipass on freenode?

**Comment by seemuth** [comment]
I changed my udev rule in ``/etc/udev/rules.d/50-mooltipass.rules``:
> ``ATTRS{idVendor}=="16d0", ATTRS{idProduct}=="09a0", MODE="0664", GROUP="plugdev"``

Now I can sometimes get ``moolticuted`` to connect to my Mini by unplugging the Mini, waiting a few minutes, plugging it back in, and waiting a few more minutes.

This process doesn't seem to always work, though.

**Comment by seemuth** [comment]
I'm digging in to the issue, and I found that ``MPDevice_linux::usbReceiveCb`` repeatedly reports a transfer status of ``LIBUSB_TRANSFER_TIMED_OUT``.

When ``moolticuted`` successfully communicates with the Mini, the transfer status is sometimes ``LIBUSB_TRANSFER_TIMED_OUT``, interspersed with successful transfers.

**Comment by seemuth** [comment]
I just tried out the new MooltiApp, and so far that works great! I'm good to go for now. Thanks!
