### ISSUE TITLE
Disable update notification

### ISSUE THREAD

**Issue by NicoHood** [raoulh/moolticute#42]
I am running the latest aur version for archlinux. The app showed me that its up to date. Such kind of information and mechanisms should be able to disable completely on distribution with a central software repository.

**Comment by raoulh** [comment]
already fixed in 1c1c827fa5076d3dde565803443f3428fb9e39e6. As for the archlinux packaging, that does not come from me, so this bug report does not apply here.

**Comment by NicoHood** [comment]
Its still in the beta 0.7, is this possible?

Also what I mean is that there should be a compile time option to disable the update check at all. Even when updates **are available**. Because then your distribution will notify you about the new version, not that application as its done on windows systems.

**Comment by limpkin** [comment]
well... it's open source...

**Comment by raoulh** [comment]
The latest released version does mean it's always git master...
As for the option to disable version check, it's up to the packager to do that. If you install by hand like it's written on the readme it's a good feature to have.

**Comment by NicoHood** [comment]
Where is this written in the readme? I can only see a make instruction there, also done in the PKGBUILD:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=moolticute#n32

**Comment by raoulh** [comment]
Really?.......

https://github.com/raoulh/moolticute/blob/master/README.md#how-to-build

**Comment by NicoHood** [comment]
@raoulh yes this is exactly what I mean. There is no information about

> If you install by hand like it's written on the readme it's a good feature to have.

I think we misunderstand. I think the feature is not implemented yet to disable the update check. Or if so I dont know which compile time variable to set to do so. Otherwise treat this issue as feature request please.

**Comment by raoulh** [comment]
Ok, to be short on this never ending discussion:
There is no option. I won't implement any, that's the job of packagers if they need it. (patch are welcome if the PR is correct and non intrusive).
End of discussion.
