### ISSUE TITLE
Closing unofficial firefox extension crashes moolticuted & app on win10 x64

### ISSUE THREAD

**Issue by limpkin** [raoulh/moolticute#8]
steps to reproduce the problem:

using https://calaos.fr/mooltipass/windows/moolticute_setup_v0.1.24-alpha.exe
browse to about:debugging#addons at FF 48
click on Enable Add-on debugging
click "load temporary add-on"
select manifest.json from the chrome_extension folder from https://github.com/Gastonius/mooltipass
click on the extension icon, click on settings
select "use moolticute instead of chrome app..."
go back to the about:debugging#addons and click on "reload" for the mooltipass extension
visit the website of interest, DO NOT accept the prompt on the device, don't let it time out
close firefox

**Comment by raoulh** [comment]
fixed in https://github.com/raoulh/moolticute/commit/d6059761ebc7996b75e94fd7efacca3bc04d12e6
