### ISSUE TITLE
Issues on debian

### ISSUE THREAD

**Issue by limpkin** [raoulh/moolticute#88]
1) right clicking on the tray icon: first item is empty:

![image](https://user-images.githubusercontent.com/6170291/29981840-7a048b60-8f4f-11e7-96af-e085a9700277.png)

2) unplugging the mooltipass: moolticute does not detect the disconnected event

3) first MoolticuteApp start: displayed screen is "The Moolticute deamon is not running" even though MoolticuteApp has started it... but disappears after 40-50 seconds -- SAME FOR MACOS

4) linux: change update notification to download the update file.

**Comment by raoulh** [comment]
1. On linux, desktops does not support custom widgets in QMenu/QSystemTray. This should be removed on linux.

2. bug

3. bug, also happens on macos
