### ISSUE TITLE
Windows: MC doesn't autostart after installation

### ISSUE THREAD

**Issue by limpkin** [raoulh/moolticute#93]
I had to actually launch it manually even with :

![image](https://user-images.githubusercontent.com/6170291/30220893-98e2a7f2-94c1-11e7-99a6-789f576a9174.png)

... and when i clicked "enable" it actually asked me to confirm autostart enabling

**Comment by raoulh** [comment]
Works for me

--
Raoul Hecky

2017-09-08 18:14 GMT+02:00 Mathieu <notifications@github.com>:

**Comment by limpkin** [comment]
can you delete that register key, delete mc, try again?

**Comment by raoulh** [comment]
done and it works perfectly

--
Raoul Hecky

2017-09-08 20:34 GMT+02:00 Mathieu <notifications@github.com>:

**Comment by limpkin** [comment]
by autostart I mean after computer boot btw

**Comment by raoulh** [comment]
Yes it works

--
Raoul Hecky

2017-09-08 22:14 GMT+02:00 Mathieu <notifications@github.com>:
